name: "Release"

on:
  push:
    branches: ["main"]
    paths: ["corpus/**", "glossary/**", "fonts/**", "pack.json"]
  workflow_dispatch:

permissions: {}

jobs:
  release:
    uses: "ashdam/ffxiv-language-pack-ci/.github/workflows/release.yml@main"
    permissions:
      contents: "write"
    with:
      language: "pt-br"
    secrets: "inherit"
