name: "Validate"

on:
  pull_request:

permissions: {}

jobs:
  validate:
    uses: "ashdam/ffxiv-language-pack-ci/.github/workflows/validate.yml@main"
    permissions:
      contents: "read"
      pull-requests: "write"
    with:
      language: "pt-br"
    secrets: "inherit"
